version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: elasticsearchlocal
    build:
      context: elasticsearch/
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: ./elasticsearch
        target: /usr/share/elasticsearch/data
    networks:
      - elastic
    ports:
       - "9200:9200"
    environment: 
      ELASTIC_PASSWORD: notagoodpassword

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    container_name: kibanalocal
    build:
      context: kibana/
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on: 
      - elasticsearch

  

networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch:
  

